# Generated by Django 6.0 on 2025-12-27 19:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('icon', models.CharField(default='fa-microchip', help_text='Bootstrap icon class (например: fa-microchip)', max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компонента')),
                ('power_draw', models.IntegerField(help_text='TDP или типичное потребление в Ваттах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Энергопотребление (Вт)')),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя цена (₽)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='calculator.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сборки')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание/примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('components', models.ManyToManyField(blank=True, related_name='builds', to='calculator.component', verbose_name='Компоненты')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['category'], name='calculator__categor_4f4e38_idx'),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['user'], name='calculator__user_id_49299f_idx'),
        ),
    ]
