# Generated by Django 6.0 on 2025-12-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='form_factor',
            field=models.CharField(blank=True, help_text='Форм-фактор (напр. AM5, LGA1700, ITX, ATX)', max_length=100, null=True),
        ),
    ]
