# Generated by Django 6.0 on 2026-01-05 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_component_form_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='peak_power',
            field=models.IntegerField(default=0, help_text='Максимальное потребление при пиковых нагрузках', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пиковое потребление (Вт)'),
        ),
        migrations.AddField(
            model_name='component',
            name='recommended_psu',
            field=models.IntegerField(default=0, help_text='Рекомендованная мощность блока питания для этого компонента', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рекомендованная мощность БП (Вт)'),
        ),
    ]
