# Generated by Django 6.0 on 2026-01-07 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_component_peak_power_component_recommended_psu'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='psu_wattage',
            field=models.IntegerField(default=0, help_text='Номинальная мощность для блоков питания (берёт power_draw если не указано)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мощность БП (Вт)'),
        ),
    ]
